---

ci:
  skip: [check-manifest]

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: fix-encoding-pragma

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - misc/license_header.txt

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
      - id: remove-tabs

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: [-I, .codespell.allow]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^(.*_test\.py)$
        additional_dependencies: [flake8-breakpoint, flake8-comprehensions,
                                  flake8-docstrings, flake8-eradicate,
                                  flake8-mutable]

      - id: flake8
        name: flake8-test-files
        additional_dependencies: [flake8-comprehensions, flake8-breakpoint,
                                  flake8-eradicate, flake8-mutable]
        files: ^(.*_test\.py)$

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a4'
    hooks:
      - id: pylint
        additional_dependencies: [flake8]
        # This is a slow hook, so only run this if --hook-stage manual is passed
        stages: [manual]

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
      - id: check-manifest
        additional_dependencies: ['setuptools-scm']
